-- MySQL Script generated by MySQL Workbench
-- 05/01/17 18:43:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aplicaciones_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aplicaciones_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aplicaciones_web` DEFAULT CHARACTER SET utf8 ;
USE `aplicaciones_web` ;

-- -----------------------------------------------------
-- Table `aplicaciones_web`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aplicaciones_web`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `aplicaciones_web`.`Usuarios` (
  `ID_USUARIO` INT NOT NULL,
  `USUARIO` VARCHAR(255) NOT NULL,
  `NOMBRE` VARCHAR(255) NULL,
  `APELLIDO_1` VARCHAR(255) NULL,
  `APELLIDO_2` VARCHAR(255) NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `TELEFONO` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE INDEX `Usuario_UNIQUE` (`USUARIO` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicaciones_web`.`Tipo_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aplicaciones_web`.`Tipo_Usuario` ;

CREATE TABLE IF NOT EXISTS `aplicaciones_web`.`Tipo_Usuario` (
  `ID_TIPOUSUARIO` INT NOT NULL,
  `FK_USUARIO` INT NULL,
  `TIPO_USUARIO` VARCHAR(10) NULL,
  PRIMARY KEY (`ID_TIPOUSUARIO`),
  UNIQUE INDEX `FK_USUARIO_UNIQUE` (`FK_USUARIO` ASC, `TIPO_USUARIO` ASC),
  CONSTRAINT `FK_USUARIO`
    FOREIGN KEY (`FK_USUARIO`)
    REFERENCES `aplicaciones_web`.`Usuarios` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicaciones_web`.`Password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aplicaciones_web`.`Password` ;

CREATE TABLE IF NOT EXISTS `aplicaciones_web`.`Password` (
  `ID_PASSWORD` INT NOT NULL,
  `PASSWORD_1` VARCHAR(45) NOT NULL,
  `PASSWORD_2` VARCHAR(45) NULL,
  `PASSWORD_3` VARCHAR(45) NULL,
  `FK_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_PASSWORD`),
  UNIQUE INDEX `FK_USUARIO_UNIQUE` (`FK_USUARIO` ASC),
  CONSTRAINT `FK_USUARIO_PASSWORD`
    FOREIGN KEY (`FK_USUARIO`)
    REFERENCES `aplicaciones_web`.`Usuarios` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aplicaciones_web`.`Peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aplicaciones_web`.`Peliculas` ;

CREATE TABLE IF NOT EXISTS `aplicaciones_web`.`Peliculas` (
  `ID_PELICULA` INT NOT NULL,
  `NOMBRE` VARCHAR(255) NOT NULL,
  `URL_CONT` VARCHAR(255) NOT NULL,
  `DESCRIPCION` TEXT(4000) NULL,
  `ANIO` DATE NULL,
  `DIRECTOR` VARCHAR(255) NULL,
  `ACTORES` TEXT(4000) NULL,
  `URL_PORTADA` VARCHAR(255) NULL,
  `VALORACION` INT NULL,
  PRIMARY KEY (`ID_PELICULA`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
